#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

setxkbmap br abnt2 &
st &
xsetroot -solid "#282828" &
xsetroot -cursor_name left_ptr &

bspc config border_width         	2
bspc config window_gap          	8
bspc config focused_border_color 	"#ffc24b"
bspc config normal_border_color 	"#6e6a86"

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle	 		true

bspc rule -a Firefox desktop='^2'
