#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

setxkbmap br abnt2 &
xsetroot -solid "#f7f7f7"
xsetroot -cursor_name left_ptr &
st &

bspc config border_width         	2
bspc config window_gap          	12
bspc config normal_border_color		"#f7f7f7"
bspc config focused_border_color	"#396fa3"

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle	 		true

bspc rule -a Firefox desktop='^2'
