#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

setxkbmap br abnt2 &
uxterm &
redshift -O 5400 &
xsetroot -cursor_name left_ptr &
feh --bg-scale /usr/share/backgrounds/lightgreen.jpg &
picom &
pulseaudio --daemonize=no --exit-idle-time=-1 &

bspc config border_width         	2
bspc config window_gap          	12

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle		true

bspc rule -a Firefox desktop='^2'
