call plug#begin()
	Plug 'PengJinLun/vim-auto-pairs'
	Plug 'mattn/emmet-vim'
	Plug 'vim-airline/vim-airline'
	Plug 'yassinebridi/vim-purpura'
	Plug 'ryanoasis/powerline-extra-symbols'
	Plug 'ryanoasis/vim-devicons'
	Plug 'preservim/nerdtree'
	Plug 'wuelnerdotexe/vim-enfocado'
call plug#end()

set guifont=FiraCode\ Nerd\ Font\ 14
let g:airline_left_sep = "\uE0B0"
let g:airline_right_sep = "\uE0B2"


syntax on
set number
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set termguicolors
colorscheme enfocado
set background=light

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

nnoremap <S-t> :tabedit 
nnoremap H :tabprevious <CR>
nnoremap L :tabnext <CR>
nnoremap <F2> :NERDTreeToggle <CR>
