#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

# Auto start programs
setxkbmap br abnt2 &
xsetroot -solid "#141745" &
xsetroot -cursor_name left_ptr
sakura &

# Appearence settings
bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#cccccc"
bspc config focused_border_color "#ffcc77"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
