#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		2
bspc config window_gap			0
bpsc config focused_border_color	"#00ff00"

setxkbmap br abnt2 &
xst &
feh --bg-scale "/usr/share/backgrounds/clean.jpg" &
xsetroot -cursor_name left_ptr &
pulseaudio &

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle	 	true

bspc rule -a Firefox desktop='^2'
