# Colorscheme
colorscheme cherry

# Tab
set-option global tabstop 4
set-option global indentwidth 4

# Status bar on top
set-option global ui_options terminal_status_on_top=true

# Display line numbers
add-highlighter global/ number-lines -hlcursor

# Highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Wrap lines
add-highlighter global/ wrap -width 80 -marker •••

set-option global modelinefmt '[%val{bufname}] [{{mode_info}}] [%val{cursor_line}:%val{cursor_char_column}] [%sh{date +%T}]'
