#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

setxkbmap br abnt2 &
xsetroot -solid "#eeeee0" &
xsetroot -cursor_name left_ptr &
xterm &

bspc config border_width         	1
bspc config window_gap			3
bspc config normal_border_color		"#aaaaaa"
bspc config focused_border_color	"#00a000"

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle		true

bspc rule -a Firefox desktop='^2'
